### ISSUE TITLE
official repository?

### ISSUE THREAD

**Issue by joenio** [lappis-unb/holodev#2]
I'm confused, the oficial repository used to be https://github.com/lappis-tools/holodev not https://github.com/lappis-unb/holodev

I need help to sync the two repositories and document what this repository here means, maybe remove this repository? @chocoelho @AlessandroCaetano, can you help? After that I'll take a look at #1.

**Comment by chocoelho** [comment]
@joenio now I noticed that it's really strange. I can send the PR there as well, it'll make more sense to be on https://github.com/lappis-tools/holodev/.

**Comment by joenio** [comment]
PR was merged at official repository
